### ISSUE TITLE
CHART - UNFCU: Reversed y-axes not reversed

### ISSUE THREAD

**Issue by stguitar** [ClearPoint-Strategy/wp-clearpoint#10]
@catherine-yochum commented on [Thu Apr 07 2016](https://github.com/ClearPoint-Strategy/clearPoint10/issues/940)

cps_unfcu / LP / stage / chrome

UNFCU has several charts where the y-axes are reversed so that lower values appear above higher values. IDs: 268166, 268170, 268180, 268184, 268185, 268187

![image](https://cloud.githubusercontent.com/assets/16578954/14365241/9db831c8-fcda-11e5-95d0-3f4c11ee9226.png)

This is an option you can set in 8 but not 10. 

![image](https://cloud.githubusercontent.com/assets/16578954/14365257/aecd26d0-fcda-11e5-91a6-e328255bf29f.png)

This affects their dashboard and the strategic planning meeting they have coming up, hence the high priority. Even if this is something HighCharts just cannot do, we should let them know soon.

Thanks!

---

@catherine-yochum commented on [Mon Apr 11 2016](https://github.com/ClearPoint-Strategy/clearPoint10/issues/940#issuecomment-208326121)

This is fixed on app/stage but not the dashboard, as I mentioned in my email this morning.

**Comment by catherine-yochum** [comment]
Fixed! Thank you!
