### ISSUE TITLE
Chrome Plugin - ClearPoint formatting changes when plugin installed

### ISSUE THREAD

**Issue by catherine-yochum** [ClearPoint-Strategy/wp-clearpoint#3]
Hi Steven,

Below are the major formatting issues I'm seeing after having installed the plugin. The login page does not look as clean and the blog posts bleed over onto a second row, and in pop-up windows in ClearPoint 8, the fonts and spacing become much larger than they should be.

Thanks for your help with this!

![no exten 1](https://cloud.githubusercontent.com/assets/16578954/12148503/d20f6006-b46c-11e5-9e94-38f2e28562fd.jpg)
![no exten 2](https://cloud.githubusercontent.com/assets/16578954/12148504/d20f87f2-b46c-11e5-92d0-421da9e7d6fd.jpg)
![with exten 1](https://cloud.githubusercontent.com/assets/16578954/12148505/d2135fa8-b46c-11e5-9eb1-56a8f15acfe2.jpg)
![with exten 2](https://cloud.githubusercontent.com/assets/16578954/12148502/d20f2442-b46c-11e5-8649-e56a7b2e8987.jpg)

**Comment by stguitar** [comment]
Seems to be working with 1.4.  Please try to use this version!


[chrome-cps.zip](https://github.com/ClearPoint-Strategy/wp-clearpoint/files/82853/chrome-cps.zip)

**Comment by catherine-yochum** [comment]
The formatting issues do seem to be fixed! Thanks.
