### ISSUE TITLE
Ft Collins - charts that were appearing are now not appearing, despite no changes made by me or FtC users

### ISSUE THREAD

**Issue by catherine-yochum** [ClearPoint-Strategy/wp-clearpoint#4]
Hi Steven,

I know I reached out to you about this issue yesterday, and I thought that it was a matter of the chart type being used in ClearPoint 8 and changes by Fort Collins users that was causing the charts to not appear, but I am seeing issues with charts that have not been changed (I checked the audit log) simply by clicking Update in Wordrpress.

Here's an example using the Net Percent Change in Local Jobs measure.

1) Clicked on the page from the Economic Health objective page (while logged into WP), here is the chart displaying nicely:
![image](https://cloud.githubusercontent.com/assets/16578954/12299125/46d8089a-b9e3-11e5-8291-d7749f38d5d6.png)

2. Clicked on Edit Page, was taken into WP - made no changes, clicked Update and then on the link to view the page
![image](https://cloud.githubusercontent.com/assets/16578954/12299188/9b31c854-b9e3-11e5-904c-a55c51e677b3.png)

3. Chart was replaced by the same red code I was seeing yesterday.
![image](https://cloud.githubusercontent.com/assets/16578954/12299233/c20f6d5a-b9e3-11e5-93af-35e0c8dee1ac.png)

The chart type in ClearPoint was originally #2 Bar with Target Line, I changed it to #1 Bar to see if that would work with no avail.There are some settings for the series (color, shape, marker) that are set; not sure if that makes a difference.

I marked this as high priority since I was supposed to reach out to Ft Collins last night about charts on the dashboard, but then we had that crazy issue and now this is happening.

Let me know what other info I can provide!

Thanks!

**Comment by stguitar** [comment]
Sorta makes sense actually - When you press Update it is trying to update the cache for this data. Let me  take a look though at why the data is coming back incorrectly

**Comment by catherine-yochum** [comment]
Thank you!!

**Comment by stguitar** [comment]
No problem.  We should have it resolved shortly.

**Comment by stguitar** [comment]
Catherine,

This should now be resolved.  There was a small setting change on the server.

Thanks,
Steven

**Comment by catherine-yochum** [comment]
Steven,

Awesome, thanks! Let me know how this email goes through.

Best,
Catherine

-----------------------------------------------------------
Catherine Yochum
ClearPoint Strategy
cyochum@clearpointstrategy.com<mailto:cyochum@clearpointstrategy.com> | 866-568-0590
www.clearpointstrategy.com<http://www.clearpointstrategy.com/> | @clearpointstrat

**Comment by catherine-yochum** [comment]
Hi Steven,

I've just gone through all the charts and found that there are 4 that are still coming up as red code. They are:
Voluntary Code Compliance (Chart ID: 122526)
Lincoln Center -  total cumulative participation (122579)
Museum of Discovery -  total cumulative participation (122598)
Natural areas programs - total cumulative participation (122653)

The latter 3 are all measures with dual y-axes, so I'm wondering if this has something to do with it. Let me know if I can provide any more info!

Thanks,
Catherine

**Comment by stguitar** [comment]
I presume all this is happening for the same period?

**Comment by stguitar** [comment]
Looking into it...

**Comment by catherine-yochum** [comment]
Steven,

Sorry, I was out on an errand during lunch and just saw your emails. Yes, I’ve been in September 2015 the whole time.

Best,
Catherine

-----------------------------------------------------------
Catherine Yochum
ClearPoint Strategy
cyochum@clearpointstrategy.com<mailto:cyochum@clearpointstrategy.com> | 866-568-0590
www.clearpointstrategy.com<http://www.clearpointstrategy.com/> | @clearpointstrat
